### ISSUE TITLE
could oci-sd export  mds metrics? 

### ISSUE THREAD

**Issue by debt2022** [sw-samuraj/oci-sd#18]
oci not support cloud exporter, so this could suuport export cloud service metrics like mysql?

**Comment by sw-samuraj** [comment]
The project is in the maintenance mode - receiving pull requests for fixes, but not actively adding any new features.

**Comment by sw-samuraj** [comment]
The project is in the maintenance mode - receiving pull requests for fixes, but not actively adding any new features.
