### ISSUE TITLE
Build Issues for Standalone

### ISSUE THREAD

**Issue by iversond** [sw-samuraj/oci-sd#7]
I'm trying to build the standalone version of `oci-sd`, but I'm getting build errors. I'm wondering if there was a dependency change that is breaking the build process.

```bash
make build
go: error loading module requirements
```

For reference, I'm building with `go1.12.7`

**Comment by sw-samuraj** [comment]
Hi @iversond. I'm now on holidays abroad without a computer. Let me check during the next week once I come back.

**Comment by tbpoetke** [comment]
also not working for me with version 1.13.7

`go build -o bin/oci-sd
go: github.com/Azure/azure-sdk-for-go@v0.0.0-20180823151430-bd73d950fa4440dae889bd9917bff7cef539f86e: invalid pseudo-version: revision is longer than canonical (bd73d950fa44)
Makefile:7: recipe for target 'build' failed
make: *** [build] Error 1
`

**Comment by tbpoetke** [comment]
after downgrading to go version 1.11 it's working .....
