### ISSUE TITLE
oci-sd crashes when instance doesn't have public ip

### ISSUE THREAD

**Issue by ColonelLanda** [sw-samuraj/oci-sd#8]
We got a situation that a returned Vnic doesn't have public ip. 
As oci-sd crashes.
The Vnic looks like:
Vnic={ 
    AvailabilityDomain=CMiL:US-ASHBURN-AD-1 
    CompartmentId=ocid1.tenancy.oc1...
    Id=ocid1.vnic.oc1....
    LifecycleState=AVAILABLE 
    SubnetId=ocid1.subnet.oc1.iad.... 
    TimeCreated=2019-11-20 08:47:44.691 +0000 UTC 
    DefinedTags=map[] 
    DisplayName=ohad-instance-20191120-1046 
    FreeformTags=map[] 
    HostnameLabel=ohad-instance-20191120-1046 
    IsPrimary=true 
    MacAddress=XXX 
    NsgIds=[] 
    PrivateIp=XXX 
    PublicIp=<nil> 
    SkipSourceDestCheck=false } 
    Etag=3bb52290 
OpcRequestId=XXX }

**Comment by sw-samuraj** [comment]
Fixed by PR #9
